apiVersion: apps/v1
kind: Deployment
metadata:
  name: counsel-cat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counsel-cat
  template:
    metadata:
      labels:
        app: counsel-cat
    spec:
      containers:
        - name: counsel-cat
          image: counsel-cat:latest
          imagePullPolicy: Never # 👈 prevents pulling from docker hub
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
